// ============================================================
// Turmas, alunos e professores — OS MESMOS da Avaliação ECL
// ============================================================
// O KitchenFlow entra com as mesmas turmas, os mesmos alunos e os mesmos
// PINs da Avaliação ECL. A lista de baixo é uma cópia da lista oficial da
// Avaliação ECL (seedAlunosReais, set/2026) e serve quando não há ligação.
// Com ligação, lê-se a lista da Avaliação ECL no Google Sheets (PINs mudados,
// alunos novos ou retirados pela coordenação) e essa manda.
// Se mudar a lista oficial na Avaliação ECL, muda-se também aqui.

export const SHEETS_AVALIACAO_ECL_URL = 'https://script.google.com/macros/s/AKfycbzFbA8e0U9GCSKyCvrCo2Pe28XgG9_UDcu7f9lqyZJ3kmWpnCj5PbWRyctLmN5OP6sC8Q/exec';

export const TURMAS_ECL = ['1º BCR', '1º ACR', '2º ACP', '3º ACP'];

export const PROFESSORES_ECL = [
  { nome: 'Rosa Almeida', pin: '1111', turmas: ['1º BCR', '1º ACR', '3º ACP'] },
  { nome: 'Mateus Freire', pin: '2468', turmas: ['2º ACP'] },
];

export const ALUNOS_ECL = [
  {turma: "1º BCR", numero: 1, nome: "Dinis Fernandes Caralinda", pin: "6875"},
  {turma: "1º BCR", numero: 2, nome: "Diogo Barbaça", pin: "1406"},
  {turma: "1º BCR", numero: 3, nome: "Diogo Miguel Bernardo Lopes", pin: "6849"},
  {turma: "1º BCR", numero: 4, nome: "Érica Melissa Oliveira Leal", pin: "6174"},
  {turma: "1º BCR", numero: 5, nome: "Euler Fernando Kateque Cariango", pin: "4657"},
  {turma: "1º BCR", numero: 6, nome: "Guilherme Heitor Pereira Coutinho", pin: "4341"},
  {turma: "1º BCR", numero: 7, nome: "Joelma Barbosa de Pina Tavares", pin: "1219"},
  {turma: "1º BCR", numero: 8, nome: "Jorgeana Patricia Tavares Varela", pin: "5977"},
  {turma: "1º BCR", numero: 9, nome: "José Luís Tavares", pin: "9152"},
  {turma: "1º BCR", numero: 10, nome: "Kiara Alexandra de White Fernandes", pin: "3087"},
  {turma: "1º BCR", numero: 11, nome: "Luana Pinto", pin: "9267"},
  {turma: "1º BCR", numero: 12, nome: "Lúcia do Espírito Santo Cabral", pin: "8900"},
  {turma: "1º BCR", numero: 13, nome: "Martim Alexandre Mendes Máximo", pin: "5580"},
  {turma: "1º BCR", numero: 14, nome: "Martim Rocha Delgado Felizardo da Silva", pin: "8078"},
  {turma: "1º BCR", numero: 15, nome: "Melissa Gaspar da Costa", pin: "1205"},
  {turma: "1º BCR", numero: 16, nome: "Orcinela Campos dos Reis da Cruz", pin: "7100"},
  {turma: "1º BCR", numero: 17, nome: "Rodrigo Pereira Carvalho", pin: "6230"},
  {turma: "1º BCR", numero: 18, nome: "Sakibul Islam Sipat", pin: "1339"},
  {turma: "1º BCR", numero: 19, nome: "Tiago Gaty Lopes", pin: "1409"},
  {turma: "1º BCR", numero: 20, nome: "Tomás Paiva Novais", pin: "5399"},
  {turma: "1º BCR", numero: 21, nome: "Kayllany Souza de Morais", pin: "6419"},
  {turma: "1º BCR", numero: 22, nome: "Letícia Filipa Correia Vicente", pin: "5244"},
  {turma: "1º ACR", numero: 1, nome: "Alexandre Miguel Carvalho Rodrigues", pin: "2425"},
  {turma: "1º ACR", numero: 2, nome: "Cristiano da Conceição Pacheco Lima", pin: "7549"},
  {turma: "1º ACR", numero: 3, nome: "Cristyan Jesus Pereira Fernandes", pin: "1145"},
  {turma: "1º ACR", numero: 4, nome: "Dalila Afonso das Neves Dias", pin: "2519"},
  {turma: "1º ACR", numero: 5, nome: "Diana Sofia Antão Ascenso", pin: "9461"},
  {turma: "1º ACR", numero: 6, nome: "Dinis Filipe Nunes Monteiro", pin: "4396"},
  {turma: "1º ACR", numero: 7, nome: "Francisco do Nascimento Varela Lopes", pin: "8049"},
  {turma: "1º ACR", numero: 8, nome: "Gustavo Morgado Chainho Antão", pin: "9513"},
  {turma: "1º ACR", numero: 9, nome: "João Rafael Ramos Gomes", pin: "7944"},
  {turma: "1º ACR", numero: 11, nome: "Lara Esteves Runa", pin: "8752"},
  {turma: "1º ACR", numero: 13, nome: "Luana Da Costa Oliveira", pin: "1823"},
  {turma: "1º ACR", numero: 14, nome: "Margarida Guerra dos Santos Duarte Costa", pin: "6762"},
  {turma: "1º ACR", numero: 15, nome: "Martim José Costa Silva", pin: "4344"},
  {turma: "1º ACR", numero: 16, nome: "Paulo Simão da Encarnação Esteves", pin: "6687"},
  {turma: "1º ACR", numero: 17, nome: "Raul Alexandre Adolfo Cotrim", pin: "9652"},
  {turma: "1º ACR", numero: 18, nome: "Susana Fernandes Sousa", pin: "3195"},
  {turma: "1º ACR", numero: 19, nome: "Vicente Castanheira Lalanda", pin: "8471"},
  {turma: "1º ACR", numero: 20, nome: "Vinicius Oliveira Cabral", pin: "9087"},
  {turma: "1º ACR", numero: 21, nome: "Yaya Konate", pin: "9936"},
  {turma: "1º ACR", numero: 99, nome: "TESTE — aluno de ensaio", pin: "9999"},
  {turma: "1º BCR", numero: 99, nome: "TESTE — aluno de ensaio", pin: "9999"},
  {turma: "2º ACP", numero: 99, nome: "TESTE — aluno de ensaio", pin: "9999"},
  {turma: "3º ACP", numero: 99, nome: "TESTE — aluno de ensaio", pin: "9999"},
  {turma: "1º ACR", numero: 88, nome: "TESTE 88 — aluno de ensaio (sem autoavaliações)", pin: "8888"},
  {turma: "1º BCR", numero: 88, nome: "TESTE 88 — aluno de ensaio (sem autoavaliações)", pin: "8888"},
  {turma: "2º ACP", numero: 88, nome: "TESTE 88 — aluno de ensaio (sem autoavaliações)", pin: "8888"},
  {turma: "3º ACP", numero: 88, nome: "TESTE 88 — aluno de ensaio (sem autoavaliações)", pin: "8888"},
  {turma: "2º ACP", numero: 1, nome: "Agnes Paola A. Conceição", pin: "4469"},
  {turma: "2º ACP", numero: 2, nome: "Alcides João S. Neto", pin: "3464"},
  {turma: "2º ACP", numero: 3, nome: "Anamar Padinha Gomes", pin: "8618"},
  {turma: "2º ACP", numero: 4, nome: "Arthur Oliveira Santos", pin: "6244"},
  {turma: "2º ACP", numero: 5, nome: "Beatriz Mendes Brito", pin: "6397"},
  {turma: "2º ACP", numero: 6, nome: "Beatriz Pompeu Pinheiro", pin: "1310"},
  {turma: "2º ACP", numero: 8, nome: "Eduardo Júnior S. Paulo", pin: "7924"},
  {turma: "2º ACP", numero: 9, nome: "Folly Orax Sallah", pin: "3616"},
  {turma: "2º ACP", numero: 10, nome: "Gonçalo Rafael Claro", pin: "5709"},
  {turma: "2º ACP", numero: 11, nome: "Gustavo Lopes Costa", pin: "3190"},
  {turma: "2º ACP", numero: 12, nome: "Isabella Medina Jurado", pin: "9527"},
  {turma: "2º ACP", numero: 14, nome: "Mafalda Resende C. Ferreira", pin: "4090"},
  {turma: "2º ACP", numero: 15, nome: "Manuel José M. Maca", pin: "9522"},
  {turma: "2º ACP", numero: 17, nome: "Neide Tavares Cardoso", pin: "8287"},
  {turma: "2º ACP", numero: 18, nome: "Raquel Luis O. Diogo", pin: "1739"},
  {turma: "2º ACP", numero: 19, nome: "Rita Maria S. Nunes", pin: "8550"},
  {turma: "2º ACP", numero: 20, nome: "Rute Santos Rodrigues", pin: "3607"},
  {turma: "2º ACP", numero: 21, nome: "Sara Andrade Arruda", pin: "2439"},
  {turma: "2º ACP", numero: 22, nome: "Telmo Márcio T. Mendes", pin: "1393"},
  {turma: "2º ACP", numero: 23, nome: "Yichen Wu", pin: "7955"},
  {turma: "3º ACP", numero: 1, nome: "Afonso Miguel C. Dias", pin: "6728"},
  {turma: "3º ACP", numero: 2, nome: "Aldmir Afonso Marques", pin: "1374"},
  {turma: "3º ACP", numero: 3, nome: "Bernardo Alexandre B. Correia", pin: "2359"},
  {turma: "3º ACP", numero: 4, nome: "Bruno Monteiro Cardoso", pin: "2792"},
  {turma: "3º ACP", numero: 5, nome: "Cilaine Espírito S. Pereira", pin: "7229"},
  {turma: "3º ACP", numero: 6, nome: "Diogo Alexandre S. Neves", pin: "6156"},
  {turma: "3º ACP", numero: 7, nome: "Djeison Patrick R. Pina", pin: "7153"},
  {turma: "3º ACP", numero: 8, nome: "Éria Santana Roberto", pin: "1579"},
  {turma: "3º ACP", numero: 9, nome: "Francisco Miguel P. Neto", pin: "1434"},
  {turma: "3º ACP", numero: 10, nome: "Hugo Guilherme B. Sequeira", pin: "8061"},
  {turma: "3º ACP", numero: 11, nome: "Íris Filipa G. Monteiro", pin: "1075"},
  {turma: "3º ACP", numero: 12, nome: "Lara Maria D. N. Machado", pin: "8915"},
  {turma: "3º ACP", numero: 13, nome: "Leonel Dino S. Tavares", pin: "5608"},
  {turma: "3º ACP", numero: 14, nome: "Leonor Sofia M. Cruz", pin: "7455"},
  {turma: "3º ACP", numero: 15, nome: "Luizito Campos Assunção", pin: "6943"},
  {turma: "3º ACP", numero: 16, nome: "Martim Fonseca M. Ramos", pin: "2136"},
  {turma: "3º ACP", numero: 17, nome: "Melisa Carine Cardoso", pin: "8177"},
  {turma: "3º ACP", numero: 18, nome: "Mishant Tamang", pin: "2738"},
  {turma: "3º ACP", numero: 19, nome: "Raquel Oliveira Pinto", pin: "4098"},
  {turma: "3º ACP", numero: 20, nome: "Ricardo Miguel G. Mendes", pin: "3014"},
  {turma: "3º ACP", numero: 21, nome: "Ronnen Alem Cardoso", pin: "9302"},
  {turma: "3º ACP", numero: 22, nome: "Vanessa Ramos Mestre", pin: "9101"},
];
